# database.py - all the SQLite database operations live here
# using sqlite3 directly rather than an ORM like SQLAlchemy
# because the data model is simple enough that raw SQL is easier to follow
# and there's no need to add an extra dependency for a prototype

import sqlite3
import json
from datetime import datetime
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import DATABASE_PATH


def get_connection():
    # row_factory makes rows come back as dict-like objects instead of tuples
    # so column access is row["column_name"] rather than row[0]
    conn = sqlite3.connect(DATABASE_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def initialise_db():
    # creates all three tables if they don't already exist
    # called once at startup so there's no need to worry about the DB being missing
    conn = get_connection()
    cursor = conn.cursor()

    # raw security events coming in from the collection layer
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS events (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp   TEXT NOT NULL,
            source      TEXT NOT NULL,
            event_type  TEXT NOT NULL,
            source_ip   TEXT,
            user_id     TEXT,
            asset       TEXT,
            details     TEXT,     -- stored as a JSON string
            processed   INTEGER DEFAULT 0
        )
    """)

    # alerts generated by the detection engine (rules or anomaly detector)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS alerts (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp       TEXT NOT NULL,
            alert_type      TEXT NOT NULL,
            severity        TEXT NOT NULL,
            source_ip       TEXT,
            user_id         TEXT,
            asset           TEXT,
            description     TEXT,
            event_ids       TEXT,   -- comma-separated IDs of the triggering events
            risk_score      INTEGER DEFAULT 0,
            acknowledged    INTEGER DEFAULT 0
        )
    """)

    # NIST risk scores - one row per alert assessed
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS risk_scores (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp       TEXT NOT NULL,
            alert_id        INTEGER,
            threat_type     TEXT NOT NULL,
            asset           TEXT,
            likelihood      TEXT NOT NULL,
            likelihood_val  INTEGER NOT NULL,
            impact          TEXT NOT NULL,
            impact_val      INTEGER NOT NULL,
            risk_score      INTEGER NOT NULL,   -- likelihood_val * impact_val (1-25)
            risk_level      TEXT NOT NULL,
            FOREIGN KEY (alert_id) REFERENCES alerts(id)
        )
    """)

    conn.commit()
    conn.close()
    print("[DB] Tables initialised OK")


# ---- event functions ----

def insert_event(timestamp, source, event_type, source_ip=None,
                 user_id=None, asset=None, details=None):
    conn = get_connection()
    conn.execute(
        """INSERT INTO events
           (timestamp, source, event_type, source_ip, user_id, asset, details)
           VALUES (?, ?, ?, ?, ?, ?, ?)""",
        (timestamp, source, event_type, source_ip, user_id, asset,
         json.dumps(details) if details else None)
    )
    conn.commit()
    conn.close()


def insert_events_bulk(event_list):
    # bulk insert is much faster than inserting one at a time
    # especially during the historical data seeding at startup
    conn = get_connection()
    rows = [
        (e["timestamp"], e["source"], e["event_type"],
         e.get("source_ip"), e.get("user_id"), e.get("asset"),
         json.dumps(e.get("details")) if e.get("details") else None)
        for e in event_list
    ]
    conn.executemany(
        """INSERT INTO events
           (timestamp, source, event_type, source_ip, user_id, asset, details)
           VALUES (?, ?, ?, ?, ?, ?, ?)""",
        rows
    )
    conn.commit()
    conn.close()


def get_recent_events(limit=50):
    conn = get_connection()
    rows = conn.execute(
        "SELECT * FROM events ORDER BY timestamp DESC LIMIT ?", (limit,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_events_filtered(event_type=None, asset=None, limit=200):
    # returns events with optional filters - used by the events page so analysts
    # can narrow down what they're looking at without wading through everything
    conn = get_connection()
    query = "SELECT * FROM events"
    params = []
    conditions = []

    if event_type and event_type != "all":
        conditions.append("event_type = ?")
        params.append(event_type)

    if asset and asset != "all":
        conditions.append("asset = ?")
        params.append(asset)

    if conditions:
        query += " WHERE " + " AND ".join(conditions)

    query += " ORDER BY timestamp DESC LIMIT ?"
    params.append(limit)

    rows = conn.execute(query, params).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_distinct_event_types():
    # used to populate the event type filter dropdown on the events page
    conn = get_connection()
    rows = conn.execute(
        "SELECT DISTINCT event_type FROM events ORDER BY event_type"
    ).fetchall()
    conn.close()
    return [r["event_type"] for r in rows]


def get_distinct_assets():
    # used to populate the asset filter dropdown on the events page
    conn = get_connection()
    rows = conn.execute(
        "SELECT DISTINCT asset FROM events WHERE asset IS NOT NULL ORDER BY asset"
    ).fetchall()
    conn.close()
    return [r["asset"] for r in rows]


def get_events_by_ip(source_ip, since_timestamp):
    # fetches events from a specific IP after a given time - used by the rule engine
    conn = get_connection()
    rows = conn.execute(
        "SELECT * FROM events WHERE source_ip = ? AND timestamp >= ? ORDER BY timestamp",
        (source_ip, since_timestamp)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_events_count_last_n(n=100):
    # returns event counts per type for the last n events - used for charts
    conn = get_connection()
    rows = conn.execute(
        """SELECT event_type, COUNT(*) as count FROM
           (SELECT event_type FROM events ORDER BY timestamp DESC LIMIT ?)
           GROUP BY event_type""",
        (n,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ---- alert functions ----

def insert_alert(timestamp, alert_type, severity, source_ip=None,
                 user_id=None, asset=None, description=None,
                 event_ids=None, risk_score=0):
    # inserts an alert and returns the new row's ID
    # the ID is needed to link the risk score record back to this alert
    conn = get_connection()
    cursor = conn.execute(
        """INSERT INTO alerts
           (timestamp, alert_type, severity, source_ip, user_id, asset,
            description, event_ids, risk_score)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (timestamp, alert_type, severity, source_ip, user_id, asset,
         description, event_ids, risk_score)
    )
    alert_id = cursor.lastrowid
    conn.commit()
    conn.close()
    return alert_id


def get_recent_alerts(limit=50):
    conn = get_connection()
    rows = conn.execute(
        "SELECT * FROM alerts ORDER BY timestamp DESC LIMIT ?", (limit,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_alerts_by_severity(severity):
    conn = get_connection()
    rows = conn.execute(
        "SELECT * FROM alerts WHERE severity = ? ORDER BY timestamp DESC",
        (severity,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def acknowledge_alert(alert_id):
    conn = get_connection()
    conn.execute(
        "UPDATE alerts SET acknowledged = 1 WHERE id = ?", (alert_id,)
    )
    conn.commit()
    conn.close()


def get_alert_counts_by_severity():
    # returns a dict of severity -> count for the dashboard summary
    conn = get_connection()
    rows = conn.execute(
        "SELECT severity, COUNT(*) as count FROM alerts GROUP BY severity"
    ).fetchall()
    conn.close()
    return {r["severity"]: r["count"] for r in rows}


def get_alerts_over_time(hours=24):
    # groups alert counts by hour for the time-series chart
    # the SQLite strftime function handles the grouping nicely
    conn = get_connection()
    rows = conn.execute(
        """SELECT strftime('%Y-%m-%d %H:00', timestamp) as hour,
                  COUNT(*) as count
           FROM alerts
           WHERE timestamp >= datetime('now', ? || ' hours')
           GROUP BY hour
           ORDER BY hour""",
        (f"-{hours}",)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ---- risk score functions ----

def insert_risk_score(timestamp, alert_id, threat_type, asset,
                      likelihood, likelihood_val, impact, impact_val,
                      risk_score, risk_level):
    conn = get_connection()
    conn.execute(
        """INSERT INTO risk_scores
           (timestamp, alert_id, threat_type, asset, likelihood, likelihood_val,
            impact, impact_val, risk_score, risk_level)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (timestamp, alert_id, threat_type, asset, likelihood, likelihood_val,
         impact, impact_val, risk_score, risk_level)
    )
    conn.commit()
    conn.close()


def get_recent_risk_scores(limit=50):
    conn = get_connection()
    rows = conn.execute(
        "SELECT * FROM risk_scores ORDER BY timestamp DESC LIMIT ?", (limit,)
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def get_risk_level_distribution():
    # counts per risk level - used for the risk distribution pie chart
    conn = get_connection()
    rows = conn.execute(
        "SELECT risk_level, COUNT(*) as count FROM risk_scores GROUP BY risk_level"
    ).fetchall()
    conn.close()
    return {r["risk_level"]: r["count"] for r in rows}


def get_dashboard_summary():
    # pulls together the key numbers for the stat cards at the top of the dashboard
    conn = get_connection()

    total_events = conn.execute("SELECT COUNT(*) FROM events").fetchone()[0]
    total_alerts = conn.execute("SELECT COUNT(*) FROM alerts").fetchone()[0]
    unacked_alerts = conn.execute(
        "SELECT COUNT(*) FROM alerts WHERE acknowledged = 0"
    ).fetchone()[0]

    # get the highest risk level currently in the system
    highest = conn.execute(
        "SELECT risk_level FROM risk_scores ORDER BY risk_score DESC LIMIT 1"
    ).fetchone()

    conn.close()

    return {
        "total_events": total_events,
        "total_alerts": total_alerts,
        "unacknowledged_alerts": unacked_alerts,
        "highest_risk_level": highest["risk_level"] if highest else "N/A",
    }
